COPY omop.DRUG_STRENGTH FROM 'C:\omop-vocabs\DRUG_STRENGTH.csv' WITH DELIMITER E'\t' CSV HEADER QUOTE E'\b' ;

COPY omop.CONCEPT FROM 'C:\omop-vocabs\CONCEPT.csv' WITH DELIMITER E'\t' CSV HEADER QUOTE E'\b' ;

COPY omop.CONCEPT_RELATIONSHIP FROM 'C:\omop-vocabs\CONCEPT_RELATIONSHIP.csv' WITH DELIMITER E'\t' CSV HEADER QUOTE E'\b' ;

COPY omop.CONCEPT_ANCESTOR FROM 'C:\omop-vocabs\CONCEPT_ANCESTOR.csv' WITH DELIMITER E'\t' CSV HEADER QUOTE E'\b' ;

COPY omop.CONCEPT_SYNONYM FROM 'C:\omop-vocabs\CONCEPT_SYNONYM.csv' WITH DELIMITER E'\t' CSV HEADER QUOTE E'\b' ;

COPY omop.VOCABULARY FROM 'C:\omop-vocabs\VOCABULARY.csv' WITH DELIMITER E'\t' CSV HEADER QUOTE E'\b' ;

COPY omop.RELATIONSHIP FROM 'C:\omop-vocabs\RELATIONSHIP.csv' WITH DELIMITER E'\t' CSV HEADER QUOTE E'\b' ;

COPY omop.CONCEPT_CLASS FROM 'C:\omop-vocabs\CONCEPT_CLASS.csv' WITH DELIMITER E'\t' CSV HEADER QUOTE E'\b' ;

COPY omop.DOMAIN FROM 'C:\omop-vocabs\DOMAIN.csv' WITH DELIMITER E'\t' CSV HEADER QUOTE E'\b' ;